### PR TITLE
Turn on Azure Pipelines CI

### LINKED ISSUE #325: Move CI over to Azure pipelines
C.f. comments in #324 and, as is our MO, because xarray did it (https://github.com/pydata/xarray/pull/3072, https://github.com/pydata/xarray/pull/3039, https://github.com/pydata/xarray/pull/3052).

I very much look forward to the day this is done...AppVeyor especially has caused us so many headaches in the past!

### PR DESCRIPTION
**Pull request by spencerahill**
Closes #325 

Likely will take a few tries to get this working.

### CODE REVIEW

**Comment by spencerahill** [comment]
OK making good progress.  Done for the night but (I think) I see the light at the end of the tunnel.

**Comment by spencerahill** [comment]
Couldn't resist a little more tinkering, and looks like its working now.

@spencerkclark would you mind looking this over at some point in next few days?  TIA.

**Review by spencerkclark — APPROVED** [review]
This looks excellent @spencerahill!  Thanks for taking the time to do this; it seems like it went relatively smoothly.  Feel free to merge.

**Comment by spencerahill** [comment]
Thanks @spencerkclark.  Yes, easier than I expected.  Which I will interpret as a good omen for Azure being reliable and easy moving forward :)

**Pull request merged**
