### PR TITLE
Fix packaging of examples

### LINKED ISSUE #149: main script not getting included with conda or pip installs
I thought that I had gotten this working back when I was working on getting our packaging in shape, but it appears not.  It is straightforward enough to do: http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

### PR DESCRIPTION
**Pull request by spencerahill**
Closes #149 plus a few other minor edits

### CODE REVIEW

**Comment by spencerahill** [comment]
Oops, misread [the docs on including scripts](http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-scripts-keyword-argument) before the most recent commit; hopefully this one fixes it

(Nice example of CI saving my tail)

**Comment by spencerahill** [comment]
Blargh forgot to rename the example notebook...this time it should *really* work 😜

**Comment by spencerkclark** [comment]
@spencerahill all good!  Any interest in checking out [pytest-ipynb](https://github.com/zonca/pytest-ipynb) to have Travis always check to make sure the example notebook runs?  I came across it yesterday, as it's used in [OceanPARCELS/parcels](https://github.com/OceanPARCELS/parcels) in their Travis build process: https://travis-ci.org/OceanPARCELS/parcels/builds/191243567

**Comment by spencerahill** [comment]
@spencerkclark nice find!  That would be very cool to eventually get configured.  Will open an issue for it.

Will merge once AppVeyor finishes, barring any objections

**Comment by spencerkclark** [comment]
Yes, this looks good to me!

**Pull request merged**
