### PR TITLE
WIP Pypi v0.1 submission

### PR DESCRIPTION
**Pull request by spencerahill**
Testbed for getting our first PyPI submission working
Using testpypi: https://wiki.python.org/moin/TestPyPI
Ignore version number; will revert to v0.1 for submission to real PyPI

Creating this PR to see if CI still works

### CODE REVIEW

**Comment by spencerahill** [comment]
Looks like I have inadvertently broken the python 3.5 CI due to a problem with the netCDF install. @spencerkclark any ideas?

**Comment by spencerkclark** [comment]
Maybe try using the conda-forge channel to install the libraries?  xarray recently switched to that.

E.g. in the YML dependency files change things to:
```
name: test_env
channels:
  - conda-forge
dependencies:
  - ...
```

**Comment by spencerahill** [comment]
@spencerkclark Great call, that did the trick.

(Still tweaking other things to get the pip install working.  And once those are fixed I will of course wait for #90 before actually releasing 0.1.)

**Comment by spencerkclark** [comment]
Awesome, this is exciting!

**Comment by spencerahill** [comment]
For future reference, when installing from testpypi, use the following command in order for package + dependencies to work: `pip install --extra-index-url https://testpypi.python.org/pypi aospy`.  Using `pip install -i https://testpypi.python.org/pypi` as suggested in the testpypi official instructions doesn't work, because the dependencies aren't on testpypi.

**Comment by spencerahill** [comment]
@spencerkclark can you please try out my pip install on one of your machines?  Seems to be working for me but want to double check.

`conda create -n testaospypip python=3.5` (or 2.7, 3.4,or 3.6)
`source activate testaospypip`
`pip install --extra-index-url https://testpypi.python.org/pypi aospy==0.1.1rc4`
`pip install pytest`
`python -c "import aospy; print(aospy.__file__.split('__init__.py')[0])"` tells you where it was installed
`py.test <that path>`

All of the dependencies should be installed via the first `pip install` command, and all of the tests should pass (less the skips/expected failures).

**Comment by spencerkclark** [comment]
Strange, I tried for python 2.7 and I'm getting some odd test failures / tracebacks.

Here is one of them (all the failures seem to be because of something like this):
```
_________________________________________________ TestBasicCalc.test_annual_mean _________________________________________________

self = <test_calc_basic.TestBasicCalc testMethod=test_annual_mean>

    def test_annual_mean(self):
        calc_int = CalcInterface(intvl_out='ann',
                                 dtype_out_time='av',
                                 **self.two_d_test_params)
        calc = Calc(calc_int)
>       calc.compute()

debug-aospy/aospy/aospy/test/test_calc_basic.py:37:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
debug-aospy/aospy/aospy/calc.py:811: in compute
    full, monthly, eddy = self._make_full_mean_eddy_ts(data)
debug-aospy/aospy/aospy/calc.py:797: in _make_full_mean_eddy_ts
    full = self._full_to_yearly_ts(full, full_dt)
debug-aospy/aospy/aospy/calc.py:703: in _full_to_yearly_ts
    arr = self._avg_by_year(arr, dt)
debug-aospy/aospy/aospy/calc.py:695: in _avg_by_year
    return ((arr*dt).groupby(yr_str).sum(TIME_STR) /
//anaconda/envs/testaospypip/lib/python2.7/site-packages/xarray/core/common.py:16: in wrapped_func
    skipna=skipna, allow_lazy=True, **kwargs)
//anaconda/envs/testaospypip/lib/python2.7/site-packages/xarray/core/groupby.py:531: in reduce
    return self.apply(reduce_array, shortcut=shortcut)
//anaconda/envs/testaospypip/lib/python2.7/site-packages/xarray/core/groupby.py:480: in apply
    combined = self._concat(applied, shortcut=shortcut)
//anaconda/envs/testaospypip/lib/python2.7/site-packages/xarray/core/groupby.py:487: in _concat
    applied_example, applied = peek_at(applied)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

iterable = <generator object <genexpr> at 0x114e433c0>

    def peek_at(iterable):
        """Returns the first value from iterable, as well as a new iterable with
        the same content as the original iterable
        """
        gen = iter(iterable)
>       peek = next(gen)
E       StopIteration

//anaconda/envs/testaospypip/lib/python2.7/site-packages/xarray/core/utils.py:90: StopIteration
------------------------------------------------------ Captured stderr call ------------------------------------------------------
INFO:root:Initializing Calc instance: Calc object: condensation_rain, example_proj, example_model, example_run (Thu Jan 12 20:15:26 2017)
Exception AttributeError: "'netcdf_file' object has no attribute 'fp'" in <bound method netcdf_file.close of <scipy.io.netcdf.netcdf_file object at 0x1102f8310>> ignored
INFO:root:Getting input data: Var instance "condensation_rain" (Thu Jan 12 20:15:26 2017)
WARNING:root:dmget command not found in this machine
INFO:root:Computing timeseries for 0004-01-01 00:00:00 -- 0006-12-31 00:00:00.
```

**Comment by spencerkclark** [comment]
@spencerahill in doing some debugging it appears that the time coordinate is being decoded incorrectly.  This leads to an empty array upon time selection, which causes the failing tests.  Here I'm getting ```1903-01-17``` etc. in the time coordinate, but we're trying to select dates using the range ```1678-01-01``` to ```1680-12-31```.
```
<xarray.DataArray 'condensation_rain' (time: 36, lat: 64, lon: 128)>
...
Coordinates:
  * lon        (lon) float64 0.0 2.812 5.625 8.438 11.25 14.06 16.88 19.69 ...
  * lat        (lat) float64 -87.86 -85.1 -82.31 -79.53 -76.74 -73.95 -71.16 ...
  * time       (time) datetime64[ns] 1903-01-17 1903-02-14 1903-03-17 ...
    sfc_area   (lat, lon) float64 3.553e+09 3.553e+09 3.553e+09 3.553e+09 ...
    land_mask  (lat, lon) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
Attributes:
    units: kg/m/m/s
    long_name: Rain from condensation
    time_avg_info: average_T1,average_T2,average_DT
    cell_methods: time: mean
```
In looking at the logic in ```calc.py``` in the install directory it appears the version of aospy that was installed here is not consistent with your latest PR (#113).  Do you know what might be causing that?

**Comment by spencerkclark** [comment]
@spencerahill everything is working now, so disregard my previous comments!  Somehow I had an old installation of aospy that pip was pointing towards (even when creating a new environment).  Once I deleted that directory, things worked as one would expect.  Apologies for the confusion.

**Comment by spencerahill** [comment]
Awesome!  Ha ya should have warned you about that; I did the same thing at first.

Cool, I'll leave this open for now and then rebase after #90 and some doc updates I have slated next.  Also will look into getting us into conda-forge, although I'll be OK if that doesn't happen before AMS now that pip looks ok.

**Comment by spencerkclark** [comment]
@spencerahill looks like we need to run the expected path names through [```os.path.normpath```](https://docs.python.org/2/library/os.path.html#os.path.normpath) before the assert statements in ```test_data_loader.py```?

Edit: Looks like there's a little more to it than that, but it has to do with differing ways of specifying paths in Windows; we may need to make some edits to the methods themselves.

**Comment by spencerahill** [comment]
@spencerkclark fixed :)

**Comment by spencerahill** [comment]
Will wait until our pending docs updates to actually create the v0.1 release, but this PR is now done in terms of incorporating the needed infrastructure for PyPI

**Pull request merged**
