### PR TITLE
Update examples Jupyter notebook and improve examples page of sphinx docs

### PR DESCRIPTION
**Pull request by spencerkclark**
I think this is mostly there, but I want to add the region example to the sphinx docs.  I'll have another look at this tomorrow morning.

### CODE REVIEW

**Comment by spencerkclark** [comment]
@spencerahill this is all set on my end.  Let me know if you have any comments on this initial content and feel free to make changes to it as you flesh out the other sections we discussed.

**Comment by spencerahill** [comment]
@spencerkclark thanks!  The only problem is that the .png image is not included.  I think if you just add it to the repo it should work.

**Comment by spencerkclark** [comment]
@spencerahill from the HTML doc build?  When I build the docs locally it gets generated dynamically (and saved using the [```@savefig```](https://github.com/ipython/ipython/wiki/Dev:-IPython-Sphinx-directive) decorator).  Is there a way I can see how it builds on ReadTheDocs?

**Comment by spencerkclark** [comment]
Do we need to add matplotlib to the docs environment?

**Comment by spencerahill** [comment]
@spencerkclark for some reason on my machine the first `make html` call generates the image but doesn't include it in the docs, but calling `make html` a second time gets it to work:

```
[spencerkclark-update-examples]shill@shillbook:~/Dropbox/py/aospy/docs$ make clean
rm -rf _build/*
[spencerkclark-update-examples]shill@shillbook:~/Dropbox/py/aospy/docs$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.5.1
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: 6 added, 0 changed, 0 removed
INFO:root:Initializing Calc instance: Calc object: total_precipitation, example_proj, example_model, example_run (Fri Jan 20 14:20:03 2017)
INFO:root:Getting input data: Var instance "condensation_rain" (Fri Jan 20 14:20:03 2017)
WARNING:root:dmget command not found in this machine
INFO:root:Getting input data: Var instance "convection_rain" (Fri Jan 20 14:20:03 2017)
WARNING:root:dmget command not found in this machine
INFO:root:Computing timeseries for 0004-01-01 00:00:00 -- 0006-12-31 00:00:00.
INFO:root:Applying desired time-reduction methods. (Fri Jan 20 14:20:03 2017)
INFO:root:Writing desired gridded outputs to disk.
WARNING:root:dmget command not found in this machine
INFO:root:	example-output/example_proj/example_model/example_run/total_precipitation/total_precipitation.ann.av.from_monthly_ts.example_model.example_run.0004-0006.nc
INFO:root:Initializing Calc instance: Calc object: total_precipitation, example_proj, example_model, example_run (Fri Jan 20 14:20:03 2017)
INFO:root:Getting input data: Var instance "condensation_rain" (Fri Jan 20 14:20:03 2017)
WARNING:root:dmget command not found in this machine
INFO:root:Getting input data: Var instance "convection_rain" (Fri Jan 20 14:20:03 2017)
WARNING:root:dmget command not found in this machine
INFO:root:Computing timeseries for 0004-01-01 00:00:00 -- 0006-12-31 00:00:00.
INFO:root:Applying desired time-reduction methods. (Fri Jan 20 14:20:04 2017)
INFO:root:Writing desired gridded outputs to disk.
WARNING:root:dmget command not found in this machine
INFO:root:	example-output/example_proj/example_model/example_run/total_precipitation/total_precipitation.ann.reg.av.from_monthly_ts.example_model.example_run.0004-0006.nc
reading sources... [100%] overview
/Users/shill/Dropbox/py/aospy/docs/examples/basics.rst:None: WARNING: image file not readable: examples/../_build/html/_static/plot_ann_total_precipitation.png
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] overview
generating indices... genindex py-modindex
highlighting module code... [100%] aospy.utils.times
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.

Build finished. The HTML pages are in _build/html.
[spencerkclark-update-examples ?]shill@shillbook:~/Dropbox/py/aospy/docs$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.5.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] examples/basics
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex py-modindex
highlighting module code... [100%] aospy.constants
writing additional pages... search
copying images... [100%] examples/../_build/html/_static/plot_ann_total_precipitation.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.
```

**Comment by spencerahill** [comment]
Honestly though I'm fine with merging and seeing if it works on RTD

**Comment by spencerkclark** [comment]
Yeah, I suspect it would be the same on my machine.  I realize now that Read the Docs doesn't build from PR's, so if you're OK with giving it a shot by merging, I say go ahead.  My gut says not having matplotlib in the environment might get us, but that's an easy fix if it happens to be a problem.

**Comment by spencerahill** [comment]
Ok good call I added matplotlib and ipython will merge after CI finishes

**Comment by spencerkclark** [comment]
Perfect, thanks!

**Pull request merged**
