### PR TITLE
MNT: Log cleaner error message when variable not found

### PR DESCRIPTION
**Pull request by spencerkclark**
@spencerahill I came upon this today and decided to try and fix it up.  The ```KeyError``` prints the string object (complete with ```'\n'``` newline characters), which is pretty messy.  In general I think it is meant to simply print the literal key that was not in the dictionary (therefore its use case is not to print a longer error message, as was done originally here):
```
(research) bash-4.1$ ipython main.py

 Project :  [Project instance "itcz"]
 Models :  [Model instance "idealized_moist_rad"]
 Runs :  [aospy.Run instance "control"]
 Ensemble members :  [None]
 Variables :  [Var instance "olr_diag", Var instance "lwdn_sfc_diag", Var instance "lwup_sfc_diag"]
 Year ranges :  [(datetime.datetime(3, 1, 1, 0, 0), datetime.datetime(6, 12, 31, 0, 0))]
 Geographical regions :  [dict_values([Geographical region "globe"])]
 Time interval of input data :  ['monthly']
 Time interval for averaging :  ['ann']
 Input data time type :  ['ts']
 Input data vertical type :  ['sigma']
 Output data time type :  [('av', 'reg.av')]
 Output data vertical type :  [False]
 Vertical levels :  [False]
 Compute this data :  True
 Time offset :  [{'days': -15}]
 Print this data :  False

INFO:root:Initializing Calc instance: Calc object: olr_diag, itcz, idealized_moist_rad, control (Tue Mar  7 11:08:41 2017)
INFO:root:Getting input data: Var instance "olr_diag" (Tue Mar  7 11:08:43 2017)
/home/skc/miniconda/envs/research/lib/python3.6/site-packages/xarray/conventions.py:389: RuntimeWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netCDF4.datetime objects instead, reason: dates out of range
  result = decode_cf_datetime(example_value, units, calendar)
/home/skc/miniconda/envs/research/lib/python3.6/site-packages/xarray/conventions.py:408: RuntimeWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netCDF4.datetime objects instead, reason: dates out of range
  calendar=self.calendar)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/home/Spencer.Clark/aospy_user/main.py in <module>()
     31
     32 if __name__ == '__main__':
---> 33     calcs = aospy_user.main(mp, prompt_verify=False, parallelize=False)

/home/Spencer.Clark/aospy_user/aospy_user/main.py in main(main_params, exec_calcs, print_table, prompt_verify, parallelize)
    187     else:
    188         calcs = cs.create_calcs(param_combos, exec_calcs=exec_calcs,
--> 189                                 print_table=print_table)
    190     return calcs

/home/Spencer.Clark/aospy_user/aospy_user/main.py in create_calcs(self, param_combos, exec_calcs, print_table)
    144                 if exec_calcs:
    145                     try:
--> 146                         calc.compute(save_tar_files=False)
    147                     except:
    148                         raise

/home/Spencer.Clark/aospy/aospy/calc.py in compute(self, save_files, save_tar_files)
    631         """Perform all desired calculations on the data and save externally."""
    632         data = self._prep_data(self._get_all_data(self.start_date,
--> 633                                                   self.end_date),
    634                                self.var.func_input_dtype)
    635         logging.info('Computing timeseries for {0} -- '

/home/Spencer.Clark/aospy/aospy/calc.py in _get_all_data(self, start_date, end_date)
    465                                                      end_date, n),
    466                                 self.var.func_input_dtype)
--> 467                 for n, var in enumerate(self.variables)]
    468
    469     def _local_ts(self, *data):

/home/Spencer.Clark/aospy/aospy/calc.py in <listcomp>(.0)
    465                                                      end_date, n),
    466                                 self.var.func_input_dtype)
--> 467                 for n, var in enumerate(self.variables)]
    468
    469     def _local_ts(self, *data):

/home/Spencer.Clark/aospy/aospy/calc.py in _get_input_data(self, var, start_date, end_date, n)
    417             data = self.data_loader.load_variable(var, start_date, end_date,
    418                                                   self.time_offset,
--> 419                                                   **self.data_loader_attrs)
    420             name = data.name
    421             data = self._add_grid_attributes(

/home/Spencer.Clark/aospy/aospy/data_loader.py in load_variable(self, var, start_date, end_date, time_offset, **DataAttrs)
    204         ds, min_year = _prep_time_data(ds)
    205         ds = set_grid_attrs_as_coords(ds)
--> 206         da = _sel_var(ds, var)
    207         da = self._maybe_apply_time_shift(da, time_offset, **DataAttrs)
    208

/home/Spencer.Clark/aospy/aospy/data_loader.py in _sel_var(ds, var)
    100             pass
    101     raise KeyError('{0} not found in '
--> 102                    'among names: {1}\n{2}'.format(var, var.names, ds))
    103
    104

KeyError: 'Var instance "olr_diag" not found in among names: (\'olr_diag\', \'olr\')\n<xarray.Dataset>\nDimensions:              (bounds: 2, lat: 64, lat_bounds: 65, lon: 128, lon_bounds: 129, pfull: 30, phalf: 31, scalar_axis: 1, time: 72)\nCoordinates:\n  * lon                  (lon) float64 0.0 2.812 5.625 8.438 11.25 14.06 ...\n  * lon_bounds           (lon_bounds) float64 -1.406 1.406 4.219 7.031 9.844 ...\n  * lat                  (lat) float64 -87.86 -85.1 -82.31 -79.53 -76.74 ...\n  * lat_bounds           (lat_bounds) float64 -90.0 -86.58 -83.76 -80.96 ...\n  * pfull                (pfull) float64 3.385 10.78 14.5 19.3 25.44 33.2 ...\n  * phalf                (phalf) float64 0.0 9.202 12.44 16.66 22.07 28.97 ...\n  * bounds               (bounds) float64 1.0 2.0\n  * scalar_axis          (scalar_axis) float64 0.0\n  * time                 (time) datetime64[ns] 1678-02-01 1678-03-01 ...\n    bk                   (time, phalf) float32 0.0 0.00920201 0.0124421 ...\n    pk                   (time, phalf) float32 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...\n    time_weights         (time) timedelta64[ns] 31 days 28 days 31 days ...\n    time_bounds          (time, bounds) datetime64[ns] 1678-01-01 1678-02-01 ...\n    raw_data_start_date  datetime64[ns] 1678-01-01\n    raw_data_end_date    datetime64[ns] 1684-01-01\nData variables:\n    height               (time, pfull, lat, lon) float32 37250.4 37250.4 ...\n    ps                   (time, lat, lon) float32 101092.0 101092.0 101092.0 ...\n    vor                  (time, pfull, lat, lon) float32 -4.04509e-05 ...\n    div                  (time, pfull, lat, lon) float32 -1.61124e-07 ...\n    ucomp                (time, pfull, lat, lon) float32 4.95135 4.94867 ...\n    vcomp                (time, pfull, lat, lon) float32 0.0392376 0.0392869 ...\n    omega                (time, pfull, lat, lon) float32 5.50104e-05 ...\n    temp                 (time, pfull, lat, lon) float32 197.327 197.327 ...\n    sphum                (time, pfull, lat, lon) float32 0.000785261 ...\n    dt_qg_condensation   (time, pfull, lat, lon) float32 -1.12023e-09 ...\n    dt_qg_convection     (time, pfull, lat, lon) float32 0.0 0.0 0.0 0.0 0.0 ...\n    convection_rain      (time, lat, lon) float32 1.38458e-08 1.38458e-08 ...\n    condensation_rain    (time, lat, lon) float32 8.69603e-06 8.6958e-06 ...\n    sw_down_sfc          (time, lat, lon) float32 4.30272 4.3026 4.30249 ...\n    lw_down_sfc          (time, lat, lon) float32 204.271 204.271 204.272 ...\n    gm_netrad_toa        (time, scalar_axis) float32 -3.18416 -6.46334 ...\n    netrad_toa           (time, lat, lon) float32 -169.196 -169.196 -169.197 ...\n    vert_int_tdt_rad     (time, lat, lon) float32 -140.144 -140.144 -140.144 ...\n    vert_int_tdtlw_rad   (time, lat, lon) float32 -146.897 -146.897 -146.897 ...\n    vert_int_tdtsw_rad   (time, lat, lon) float32 6.75283 6.75303 6.75323 ...\n    dt_tg_rad            (time, pfull, lat, lon) float32 -4.24369e-05 ...\n    dt_tg_diffusion      (time, pfull, lat, lon) float32 0.0 0.0 0.0 0.0 0.0 ...\n    dt_qg_diffusion      (time, pfull, lat, lon) float32 0.0 0.0 0.0 0.0 0.0 ...\n    dt_tg_condensation   (time, pfull, lat, lon) float32 2.78765e-06 ...\n    dt_tg_convection     (time, pfull, lat, lon) float32 0.0 0.0 0.0 0.0 0.0 ...\n    t_surf               (time, lat, lon) float32 254.236 254.236 254.236 ...\n    flux_t               (time, lat, lon) float32 -0.138892 -0.138889 ...\n    flux_lhe             (time, lat, lon) float32 -0.0315548 -0.0315541 ...\n    flux_oceanq          (time, lat, lon) float32 0.0 0.0 0.0 0.0 0.0 0.0 ...\n    qo3                  (time, pfull, lat, lon) float32 4.70588e-06 ...\n    average_T1           (time) object    1-01-01 00:00:00 ...\n    average_T2           (time) object    1-02-01 00:00:00 ...'
```

In the PR I no longer print a specific key for the KeyError, because we try multiple.  Instead I print an error message using the logging module, and raise a KeyError without a key.  I'm still not totally sure this is the most idiomatic way to handle the situation, but it's a start. What are your thoughts?  

This is what the new error message looks like:
```
(research) bash-4.1$ ipython main.py

 Project :  [Project instance "itcz"]
 Models :  [Model instance "idealized_moist_rad"]
 Runs :  [aospy.Run instance "control"]
 Ensemble members :  [None]
 Variables :  [Var instance "olr_diag", Var instance "lwdn_sfc_diag", Var instance "lwup_sfc_diag"]
 Year ranges :  [(datetime.datetime(3, 1, 1, 0, 0), datetime.datetime(6, 12, 31, 0, 0))]
 Geographical regions :  [dict_values([Geographical region "globe"])]
 Time interval of input data :  ['monthly']
 Time interval for averaging :  ['ann']
 Input data time type :  ['ts']
 Input data vertical type :  ['sigma']
 Output data time type :  [('av', 'reg.av')]
 Output data vertical type :  [False]
 Vertical levels :  [False]
 Compute this data :  True
 Time offset :  [{'days': -15}]
 Print this data :  False

INFO:root:Initializing Calc instance: Calc object: olr_diag, itcz, idealized_moist_rad, control (Tue Mar  7 11:34:17 2017)
INFO:root:Getting input data: Var instance "olr_diag" (Tue Mar  7 11:34:18 2017)
/home/skc/miniconda/envs/research/lib/python3.6/site-packages/xarray/conventions.py:389: RuntimeWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netCDF4.datetime objects instead, reason: dates out of range
  result = decode_cf_datetime(example_value, units, calendar)
/home/skc/miniconda/envs/research/lib/python3.6/site-packages/xarray/conventions.py:408: RuntimeWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netCDF4.datetime objects instead, reason: dates out of range
  calendar=self.calendar)
ERROR:root:Var instance "olr_diag" not found among names: ('olr_diag', 'olr') in
<xarray.Dataset>
Dimensions:              (bounds: 2, lat: 64, lat_bounds: 65, lon: 128, lon_bounds: 129, pfull: 30, phalf: 31, scalar_axis: 1, time: 72)
Coordinates:
  * lon                  (lon) float64 0.0 2.812 5.625 8.438 11.25 14.06 ...
  * lon_bounds           (lon_bounds) float64 -1.406 1.406 4.219 7.031 9.844 ...
  * lat                  (lat) float64 -87.86 -85.1 -82.31 -79.53 -76.74 ...
  * lat_bounds           (lat_bounds) float64 -90.0 -86.58 -83.76 -80.96 ...
  * pfull                (pfull) float64 3.385 10.78 14.5 19.3 25.44 33.2 ...
  * phalf                (phalf) float64 0.0 9.202 12.44 16.66 22.07 28.97 ...
  * bounds               (bounds) float64 1.0 2.0
  * scalar_axis          (scalar_axis) float64 0.0
  * time                 (time) datetime64[ns] 1678-02-01 1678-03-01 ...
    bk                   (time, phalf) float32 0.0 0.00920201 0.0124421 ...
    pk                   (time, phalf) float32 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
    time_weights         (time) timedelta64[ns] 31 days 28 days 31 days ...
    time_bounds          (time, bounds) datetime64[ns] 1678-01-01 1678-02-01 ...
    raw_data_start_date  datetime64[ns] 1678-01-01
    raw_data_end_date    datetime64[ns] 1684-01-01
Data variables:
    height               (time, pfull, lat, lon) float32 37250.4 37250.4 ...
    ps                   (time, lat, lon) float32 101092.0 101092.0 101092.0 ...
    vor                  (time, pfull, lat, lon) float32 -4.04509e-05 ...
    div                  (time, pfull, lat, lon) float32 -1.61124e-07 ...
    ucomp                (time, pfull, lat, lon) float32 4.95135 4.94867 ...
    vcomp                (time, pfull, lat, lon) float32 0.0392376 0.0392869 ...
    omega                (time, pfull, lat, lon) float32 5.50104e-05 ...
    temp                 (time, pfull, lat, lon) float32 197.327 197.327 ...
    sphum                (time, pfull, lat, lon) float32 0.000785261 ...
    dt_qg_condensation   (time, pfull, lat, lon) float32 -1.12023e-09 ...
    dt_qg_convection     (time, pfull, lat, lon) float32 0.0 0.0 0.0 0.0 0.0 ...
    convection_rain      (time, lat, lon) float32 1.38458e-08 1.38458e-08 ...
    condensation_rain    (time, lat, lon) float32 8.69603e-06 8.6958e-06 ...
    sw_down_sfc          (time, lat, lon) float32 4.30272 4.3026 4.30249 ...
    lw_down_sfc          (time, lat, lon) float32 204.271 204.271 204.272 ...
    gm_netrad_toa        (time, scalar_axis) float32 -3.18416 -6.46334 ...
    netrad_toa           (time, lat, lon) float32 -169.196 -169.196 -169.197 ...
    vert_int_tdt_rad     (time, lat, lon) float32 -140.144 -140.144 -140.144 ...
    vert_int_tdtlw_rad   (time, lat, lon) float32 -146.897 -146.897 -146.897 ...
    vert_int_tdtsw_rad   (time, lat, lon) float32 6.75283 6.75303 6.75323 ...
    dt_tg_rad            (time, pfull, lat, lon) float32 -4.24369e-05 ...
    dt_tg_diffusion      (time, pfull, lat, lon) float32 0.0 0.0 0.0 0.0 0.0 ...
    dt_qg_diffusion      (time, pfull, lat, lon) float32 0.0 0.0 0.0 0.0 0.0 ...
    dt_tg_condensation   (time, pfull, lat, lon) float32 2.78765e-06 ...
    dt_tg_convection     (time, pfull, lat, lon) float32 0.0 0.0 0.0 0.0 0.0 ...
    t_surf               (time, lat, lon) float32 254.236 254.236 254.236 ...
    flux_t               (time, lat, lon) float32 -0.138892 -0.138889 ...
    flux_lhe             (time, lat, lon) float32 -0.0315548 -0.0315541 ...
    flux_oceanq          (time, lat, lon) float32 0.0 0.0 0.0 0.0 0.0 0.0 ...
    qo3                  (time, pfull, lat, lon) float32 4.70588e-06 ...
    average_T1           (time) object    1-01-01 00:00:00 ...
    average_T2           (time) object    1-02-01 00:00:00 ...
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/home/Spencer.Clark/aospy_user/main.py in <module>()
     31
     32 if __name__ == '__main__':
---> 33     calcs = aospy_user.main(mp, prompt_verify=False, parallelize=False)

/home/Spencer.Clark/aospy_user/aospy_user/main.py in main(main_params, exec_calcs, print_table, prompt_verify, parallelize)
    187     else:
    188         calcs = cs.create_calcs(param_combos, exec_calcs=exec_calcs,
--> 189                                 print_table=print_table)
    190     return calcs

/home/Spencer.Clark/aospy_user/aospy_user/main.py in create_calcs(self, param_combos, exec_calcs, print_table)
    144                 if exec_calcs:
    145                     try:
--> 146                         calc.compute(save_tar_files=False)
    147                     except:
    148                         raise

/home/Spencer.Clark/aospy/aospy/calc.py in compute(self, save_files, save_tar_files)
    631         """Perform all desired calculations on the data and save externally."""
    632         data = self._prep_data(self._get_all_data(self.start_date,
--> 633                                                   self.end_date),
    634                                self.var.func_input_dtype)
    635         logging.info('Computing timeseries for {0} -- '

/home/Spencer.Clark/aospy/aospy/calc.py in _get_all_data(self, start_date, end_date)
    465                                                      end_date, n),
    466                                 self.var.func_input_dtype)
--> 467                 for n, var in enumerate(self.variables)]
    468
    469     def _local_ts(self, *data):

/home/Spencer.Clark/aospy/aospy/calc.py in <listcomp>(.0)
    465                                                      end_date, n),
    466                                 self.var.func_input_dtype)
--> 467                 for n, var in enumerate(self.variables)]
    468
    469     def _local_ts(self, *data):

/home/Spencer.Clark/aospy/aospy/calc.py in _get_input_data(self, var, start_date, end_date, n)
    417             data = self.data_loader.load_variable(var, start_date, end_date,
    418                                                   self.time_offset,
--> 419                                                   **self.data_loader_attrs)
    420             name = data.name
    421             data = self._add_grid_attributes(

/home/Spencer.Clark/aospy/aospy/data_loader.py in load_variable(self, var, start_date, end_date, time_offset, **DataAttrs)
    205         ds, min_year = _prep_time_data(ds)
    206         ds = set_grid_attrs_as_coords(ds)
--> 207         da = _sel_var(ds, var)
    208         da = self._maybe_apply_time_shift(da, time_offset, **DataAttrs)
    209

/home/Spencer.Clark/aospy/aospy/data_loader.py in _sel_var(ds, var)
    101     logging.error('{0} not found '
    102                    'among names: {1} in\n{2}'.format(var, var.names, ds))
--> 103     raise KeyError
    104
    105

KeyError:
```

### CODE REVIEW

**Comment by spencerahill** [comment]
Is this [SO question](http://stackoverflow.com/questions/11525321/python-3-exception-not-printing-new-line) relevant?

Will return to this.

**Comment by spencerkclark** [comment]
I think this is actually specific to using ```KeyError```.  Other exception types appear to work OK:
```
In [1]: raise(KeyError('a\nb'))
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-02007c0d410a> in <module>()
----> 1 raise(KeyError('a\nb'))

KeyError: 'a\nb'

In [2]: raise(LookupError('a\nb'))
---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
<ipython-input-2-ce1539293e0c> in <module>()
----> 1 raise(LookupError('a\nb'))

LookupError: a
b

In [3]: raise(ValueError('a\nb'))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-21650602bc3d> in <module>()
----> 1 raise(ValueError('a\nb'))

ValueError: a
b
```

I propose we use the more general [```LookupError```](https://docs.python.org/2/library/exceptions.html#exceptions.LookupError), which is the [super class](https://docs.python.org/2/library/exceptions.html#exception-hierarchy) to ```KeyError```:

```
(research) bash-4.1$ ipython main.py

 Project :  [Project instance "itcz"]
 Models :  [Model instance "idealized_moist_rad"]
 Runs :  [aospy.Run instance "control"]
 Ensemble members :  [None]
 Variables :  [Var instance "vcomp"]
 Year ranges :  [(datetime.datetime(3, 1, 1, 0, 0), datetime.datetime(6, 12, 31, 0, 0))]
 Geographical regions :  [dict_values([Geographical region "globe"])]
 Time interval of input data :  ['rad_monthly']
 Time interval for averaging :  ['ann']
 Input data time type :  ['ts']
 Input data vertical type :  ['sigma']
 Output data time type :  [('av', 'reg.av')]
 Output data vertical type :  [False]
 Vertical levels :  [False]
 Compute this data :  True
 Time offset :  [{'days': -15}]
 Print this data :  False

INFO:root:Initializing Calc instance: Calc object: vcomp, itcz, idealized_moist_rad, control (Tue Mar  7 16:40:38 2017)
INFO:root:Getting input data: Var instance "vcomp" (Tue Mar  7 16:40:38 2017)
/home/skc/miniconda/envs/research/lib/python3.6/site-packages/xarray/conventions.py:389: RuntimeWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netCDF4.datetime objects instead, reason: dates out of range
  result = decode_cf_datetime(example_value, units, calendar)
/home/skc/miniconda/envs/research/lib/python3.6/site-packages/xarray/conventions.py:408: RuntimeWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netCDF4.datetime objects instead, reason: dates out of range
  calendar=self.calendar)
---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
/home/Spencer.Clark/aospy_user/main.py in <module>()
     35
     36 if __name__ == '__main__':
---> 37     calcs = aospy_user.main(mp, prompt_verify=False, parallelize=False)

/home/Spencer.Clark/aospy_user/aospy_user/main.py in main(main_params, exec_calcs, print_table, prompt_verify, parallelize)
    187     else:
    188         calcs = cs.create_calcs(param_combos, exec_calcs=exec_calcs,
--> 189                                 print_table=print_table)
    190     return calcs

/home/Spencer.Clark/aospy_user/aospy_user/main.py in create_calcs(self, param_combos, exec_calcs, print_table)
    144                 if exec_calcs:
    145                     try:
--> 146                         calc.compute(save_tar_files=False)
    147                     except:
    148                         raise

/home/Spencer.Clark/aospy/aospy/calc.py in compute(self, save_files, save_tar_files)
    631         """Perform all desired calculations on the data and save externally."""
    632         data = self._prep_data(self._get_all_data(self.start_date,
--> 633                                                   self.end_date),
    634                                self.var.func_input_dtype)
    635         logging.info('Computing timeseries for {0} -- '

/home/Spencer.Clark/aospy/aospy/calc.py in _get_all_data(self, start_date, end_date)
    465                                                      end_date, n),
    466                                 self.var.func_input_dtype)
--> 467                 for n, var in enumerate(self.variables)]
    468
    469     def _local_ts(self, *data):

/home/Spencer.Clark/aospy/aospy/calc.py in <listcomp>(.0)
    465                                                      end_date, n),
    466                                 self.var.func_input_dtype)
--> 467                 for n, var in enumerate(self.variables)]
    468
    469     def _local_ts(self, *data):

/home/Spencer.Clark/aospy/aospy/calc.py in _get_input_data(self, var, start_date, end_date, n)
    417             data = self.data_loader.load_variable(var, start_date, end_date,
    418                                                   self.time_offset,
--> 419                                                   **self.data_loader_attrs)
    420             name = data.name
    421             data = self._add_grid_attributes(

/home/Spencer.Clark/aospy/aospy/data_loader.py in load_variable(self, var, start_date, end_date, time_offset, **DataAttrs)
    207         ds, min_year = _prep_time_data(ds)
    208         ds = set_grid_attrs_as_coords(ds)
--> 209         da = _sel_var(ds, var)
    210         da = self._maybe_apply_time_shift(da, time_offset, **DataAttrs)
    211

/home/Spencer.Clark/aospy/aospy/data_loader.py in _sel_var(ds, var)
    100             pass
    101     msg = '{0} not found among names: {1} in\n{2}'.format(var, var.names, ds)
--> 102     raise LookupError(msg)
    103     # logging.error('{0} not found '
    104     #               'among names: {1} in\n{2}'.format(var, var.names, ds))

LookupError: Var instance "vcomp" not found among names: ('vcomp', 'va') in
<xarray.Dataset>
Dimensions:              (bounds: 2, lat: 64, lat_bounds: 65, lon: 128, lon_bounds: 129, pfull: 30, phalf: 31, time: 72)
Coordinates:
  * lon                  (lon) float64 0.0 2.812 5.625 8.438 11.25 14.06 ...
  * lon_bounds           (lon_bounds) float64 -1.406 1.406 4.219 7.031 9.844 ...
  * lat                  (lat) float64 -87.86 -85.1 -82.31 -79.53 -76.74 ...
  * lat_bounds           (lat_bounds) float64 -90.0 -86.58 -83.76 -80.96 ...
  * bounds               (bounds) float64 1.0 2.0
  * pfull                (pfull) float64 3.385 10.78 14.5 19.3 25.44 33.2 ...
  * phalf                (phalf) float64 0.0 9.202 12.44 16.66 22.07 28.97 ...
  * time                 (time) datetime64[ns] 1678-02-01 1678-03-01 ...
    time_weights         (time) timedelta64[ns] 31 days 28 days 31 days ...
    time_bounds          (time, bounds) datetime64[ns] 1678-01-01 1678-02-01 ...
    raw_data_start_date  datetime64[ns] 1678-01-01
    raw_data_end_date    datetime64[ns] 1684-01-01
Data variables:
    olr                  (time, lat, lon) float32 213.384 213.384 213.384 ...
    tdt_lw               (time, pfull, lat, lon) float32 -5.151e-05 ...
    tdt_sw               (time, pfull, lat, lon) float32 9.06734e-06 ...
    allradp              (time, pfull, lat, lon) float32 -4.24427e-05 ...
    lwdn_sfc             (time, lat, lon) float32 204.276 204.276 204.277 ...
    lwup_sfc             (time, lat, lon) float32 270.763 270.763 270.764 ...
    swdn_sfc             (time, lat, lon) float32 5.91571 5.91556 5.9154 ...
    swup_sfc             (time, lat, lon) float32 1.61203 1.61199 1.61195 ...
    swdn_toa             (time, lat, lon) float32 16.1456 16.1456 16.1456 ...
    swup_toa             (time, lat, lon) float32 5.08754 5.08745 5.08736 ...
    heat2d_rad           (time, lat, lon) float32 -140.148 -140.148 -140.148 ...
    heat2d_sw            (time, lat, lon) float32 6.75434 6.75454 6.75475 ...
    average_T1           (time) object    1-01-01 00:00:00 ...
    average_T2           (time) object    1-02-01 00:00:00 ...
```

**Comment by spencerkclark** [comment]
From deep in the [core of python (lines 1270-1285)](https://hg.python.org/cpython/file/c6880edaf6f3/Objects/exceptions.c) there is an explanation for this ([undocumented?](https://docs.python.org/2/library/exceptions.html#exceptions.KeyError)) behavior:
```
KeyError_str(PyBaseExceptionObject *self)
{
    /* If args is a tuple of exactly one item, apply repr to args[0].
       This is done so that e.g. the exception raised by {}[''] prints
         KeyError: ''
       rather than the confusing
         KeyError
       alone.  The downside is that if KeyError is raised with an explanatory
       string, that string will be displayed in quotes.  Too bad.
       If args is anything else, use the default BaseException__str__().
    */
    if (PyTuple_GET_SIZE(self->args) == 1) {
        return PyObject_Repr(PyTuple_GET_ITEM(self->args, 0));
    }
    return BaseException_str(self);
}
```

So for a ```KeyError``` the repr of the message is printed, rather than the message itself:
```
In [1]: print('a\nb'.__repr__())
'a\nb'

In [2]: print('a\nb')
a
b
```

**Comment by spencerahill** [comment]
Wow, thanks for the deep dive!  So this KeyError-specificity is deliberate in order to handle empty strings as keys (right?).

FYI they have migrated the official CPython repo to github: https://github.com/python/cpython

You might consider raising an issue in that repo about the lack of documentation, which I agree is confusing.  Or maybe follow their instructions re: improving documentation http://cpython-devguide.readthedocs.io/docquality.html

Or don't worry about it now that we have it figured out 😄 

I agree, `LookupError` is a good solution.

**Comment by spencerkclark** [comment]
> So this KeyError-specificity is deliberate in order to handle empty strings as keys (right?).

Exactly.

> FYI they have migrated the official CPython repo to github: https://github.com/python/cpython  You might consider raising an issue in that repo about the lack of documentation, which I agree is confusing.

Good to know!  I'm inclined to leave them alone for now.  Maybe if I have time later I'll give it a shot, but it's not a huge priority for me at the moment.  This PR is searchable, so people might stumble upon this organically through Google if they run into a similar issue :)

I'll update things shortly using ```LookupError```.

**Comment by spencerahill** [comment]
Perfect, thanks!  I'd say this is small and obscure enough that we can skip the what's new entry.

**Pull request merged**
