### PR TITLE
Fix existing flake8 errors and add flake8 check and verbose flag to CI

### LINKED ISSUE #234: Add pep8 check to CI
Let's leave the style nitpicks to the robots.  Should be easily able to adapt xarray's here: https://github.com/pydata/xarray/blob/master/.travis.yml#L94

### PR DESCRIPTION
**Pull request by micahkim23**
Closes #234

### CODE REVIEW

**Review by spencerkclark — DISMISSED** [review]

**Comment by spencerahill** [comment]
Thanks @micahkim23

So we're getting an error message on the `git diff` call: https://travis-ci.org/spencerahill/aospy/jobs/304612704#L1101.  From that log:

```
$ git diff upstream/develop **/*py | flake8 --diff --exit-zero || true
fatal: ambiguous argument 'upstream/develop': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
```

But I now see that xarray's tests (from which we stole that line, replacing `upstream/master` with `upstream/develop` have the exact same error: https://travis-ci.org/pydata/xarray/jobs/304072446#L4089

The command does work on my local machine, however (with `upstream/develop`), in that I don't get this error message.  But in playing around with it briefly, I couldn't actually trigger a non-zero exit status.  I'm new to `git diff`, so I doubt it's something too difficult.  But we should get this sorted out before merging this.

@micahkim23 so you might have to read up on `git diff` a bit to figure this out.

**Comment by spencerkclark** [comment]
Is it simply that there is no remote named `upstream` on Travis?  Agreed that we should try to fix this.

**Comment by spencerkclark** [comment]
Naively I might try adding something like:
```
- git remote add upstream https://github.com/spencerahill/aospy.git
```
before the following line in our `.travis.yml`: https://github.com/spencerahill/aospy/blob/b3bbd20f9ffc0e700ee8e8e0b35cb56a63d5753c/.travis.yml#L44

**Comment by spencerahill** [comment]
@spencerkclark good idea.

Separately, see #238 re: the test failures

**Comment by micahkim23** [comment]
I think the appveyor failures will be fixed with #240 and the commit that closes the files in `test_calc_basic.py`. Should we wait until that pr is merged or should I just make the same change here?

**Comment by spencerkclark** [comment]
Thanks @micahkim23!  If it's not too much trouble, go ahead and fix the failing Appveyor tests following https://github.com/spencerahill/aospy/pull/240/commits/a3a3753c6de89592b99346aadf86355166be3a4f.  It will be good to get the `flake8` check in before we merge further PR's.  I may do some more work in #240, so it might be open a bit longer (and I'm totally cool merging my branch with the latest develop branch once this gets merged).

**Comment by spencerahill** [comment]
@micahkim23 this is great!

>go ahead and fix the failing Appveyor tests following a3a3753. It will be good to get the flake8 check in before we merge further PR's

I agree with this.  Excited to merge once this is addressed.

**Comment by micahkim23** [comment]
Now the only appveyor failure is the issue described in #238.

**Comment by spencerahill** [comment]
>Now the only appveyor failure is the issue described in #238.

Exactly.  So in it goes!  Thanks @micahkim23 for the heavy lifting and @spencerkclark for the review

**Pull request merged**
