### PR TITLE
Fix distributed timeout errors

### LINKED ISSUE #259: Travis intermittent failures on our submit_mult_calcs external client tests in 2.7 only
This is starting to happen with more regularity now, e.g. https://travis-ci.org/spencerahill/aospy/jobs/356503697#L854.  I've pasted the full error message below.

Further motivation to drop 2.7? :stuck_out_tongue_winking_eye:  c.f. #256 

```
==================================== ERRORS ====================================
___ ERROR at setup of test_submit_mult_calcs_external_client[exec_options0] ____
    @pytest.fixture
    def external_client():
        # Explicitly specify we want only 4 workers so that when running on
        # Travis we don't request too many.
>       cluster = distributed.LocalCluster(n_workers=4)
aospy/test/test_automate.py:221: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../miniconda/envs/test_env/lib/python2.7/site-packages/distributed/deploy/local.py:127: in __init__
    self.start(ip=ip, n_workers=n_workers)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/distributed/deploy/local.py:145: in start
    sync(self.loop, self._start, **kwargs)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/distributed/utils.py:254: in sync
    six.reraise(*error[0])
../../../miniconda/envs/test_env/lib/python2.7/site-packages/distributed/utils.py:238: in f
    result[0] = yield make_coro()
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:1099: in run
    value = future.result()
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py:260: in result
    raise_exc_info(self._exc_info)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:1107: in run
    yielded = self.gen.throw(*exc_info)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/distributed/deploy/local.py:163: in _start
    yield [self._start_worker(**self.worker_kwargs) for i in range(n_workers)]
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:1099: in run
    value = future.result()
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py:260: in result
    raise_exc_info(self._exc_info)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:849: in callback
    result_list.append(f.result())
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py:260: in result
    raise_exc_info(self._exc_info)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:1107: in run
    yielded = self.gen.throw(*exc_info)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/distributed/deploy/local.py:180: in _start_worker
    yield w._start()
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:1099: in run
    value = future.result()
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py:260: in result
    raise_exc_info(self._exc_info)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:1107: in run
    yielded = self.gen.throw(*exc_info)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/distributed/nanny.py:155: in _start
    response = yield self.instantiate()
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:1099: in run
    value = future.result()
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py:260: in result
    raise_exc_info(self._exc_info)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:1107: in run
    yielded = self.gen.throw(*exc_info)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/distributed/nanny.py:223: in instantiate
    self.process.start()
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:1099: in run
    value = future.result()
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py:260: in result
    raise_exc_info(self._exc_info)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:1107: in run
    yielded = self.gen.throw(*exc_info)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/distributed/nanny.py:363: in start
    self._wait_until_started())
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:1099: in run
    value = future.result()
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py:260: in result
    raise_exc_info(self._exc_info)
../../../miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py:1113: in run
    yielded = self.gen.send(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <distributed.nanny.WorkerProcess object at 0x7f202dbe8e10>
    @gen.coroutine
    def _wait_until_started(self):
        delay = 0.05
        while True:
            if self.status != 'starting':
                return
            try:
                msg = self.init_result_q.get_nowait()
>               assert msg == 'started', msg
E               AssertionError: {'dir': '/home/travis/build/spencerahill/aospy/dask-worker-space/worker-mIruo9', 'address': 'tcp://127.0.0.1:36375'}
../../../miniconda/envs/test_env/lib/python2.7/site-packages/distributed/nanny.py:471: AssertionError
---------------------------- Captured stderr setup -----------------------------
distributed.utils - ERROR - {'dir': '/home/travis/build/spencerahill/aospy/dask-worker-space/worker-mIruo9', 'address': 'tcp://127.0.0.1:36375'}
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/distributed/deploy/local.py", line 163, in _start
    yield [self._start_worker(**self.worker_kwargs) for i in range(n_workers)]
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 849, in callback
    result_list.append(f.result())
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/distributed/deploy/local.py", line 180, in _start_worker
    yield w._start()
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/distributed/nanny.py", line 155, in _start
    response = yield self.instantiate()
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/distributed/nanny.py", line 223, in instantiate
    self.process.start()
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/distributed/nanny.py", line 363, in start
    self._wait_until_started())
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/home/travis/miniconda/envs/test_env/lib/python2.7/site-packages/distributed/nanny.py", line 471, in _wait_until_started
    assert msg == 'started', msg
AssertionError: {'dir': '/home/travis/build/spencerahill/aospy/dask-worker-space/worker-mIruo9', 'address': 'tcp://127.0.0.1:36375'}
```

### PR DESCRIPTION
**Pull request by spencerkclark**
I think this may fix #259

### CODE REVIEW

**Comment by spencerkclark** [comment]
Interesting, so the workers basically never started in the [Python 2.7 build](https://travis-ci.org/spencerahill/aospy/jobs/371699969):
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

So it's not just about being more patient...maybe we can just skip these tests on Python 2.7 for now?

**Comment by spencerahill** [comment]
Shoot.  It was good idea anyways 😃 

>So it's not just about being more patient...maybe we can just skip these tests on Python 2.7 for now?

Yes, especially since 2.7 support is on its way out anyways (#256).

**Comment by spencerkclark** [comment]
> Yes, especially since 2.7 support is on its way out anyways (#256).

Great, I added skips, which seem to be working as expected (the failures are now all #268).

**Comment by spencerahill** [comment]
Awesome, thanks!  I'll merge this first so that I can get rid of these in #268 :)

**Pull request merged**
